config/routes.rb
Blocitoff::Application.routes.draw do

  devise_for :users

  resources :users do
       resources :tasks
       match '/tasks/:id/complete' , to: 'tasks#complete', as: :complete
  end

  

authenticated :user do
  root  :to => 'tasks#index'
end   



match "about" => 'welcome#about', via: :get

root :to =>'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Post, :user_id => user.id
      can :manage, Comment, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :destroy, Post
      can :destroy, Comment
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :description, :due_date, :name, :user_id, :category

 
  belongs_to :user

  default_scope order('due_date DESC')

  def time_remaining
    today = Date.today
    created = self.created_at.to_date
    lag  = 7.days
    expiration_time = created + lag

    (expiration_time - today).to_i

  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  attr_accessible :email, :password, :password_confirmation, :remember_me


 has_many :tasks

 before_create :set_member

 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_filter :authenticate_user!
  protect_from_forgery


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!  #devise won't check public facing pages
  def index

  end

  def about
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
    authorize! :create, List
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @List = List.find(params[:id])
  end

  def destroy
  end

  def create

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @tasks = current_user.tasks
    
  end

  def new
    @task = Task.new
   
  end

  def show
    @task = Task.find(params[:id])
  end
  def edit
    @tasks = Task.find(params[:id])
  end

  def destroy
  end

  def create
    #@user = User.find(params[:user_id])
    @task = Task.new(params[:task])
    @task.user = current_user
    @task.due_date = (Date.today + 7.days)
    
    if @task.save
      flash[:notice] = "New task saved!"
      redirect_to(user_tasks_path(current_user))
    else
      flash[:error] = "Error saving task. Please try again."
      render :new
    end
  end

  def complete
    #mark all tasks as complete
    redirect_to user_tasks_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.visible_to(current_user)
  end

  def index

  end  
end

app/helpers/application_helper.rb
module ApplicationHelper

 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Bloccitoff</h1>
  <p>Bloccit is a resource for creating and destroying lists</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
         <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<div class="row">
  <div class="span8">
    <% @lists.each do |list| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to list.name, list %>
          </h4>
          <small>
            <%= list.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="span4">
    <% if can? :create, List %>
      <%= link_to "New List", new_list_path, class: 'btn btn-large btn-block' %>
    <% end %>
  </div>
</div>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1> My Tasks </h1>
<%= link_to "Create Tasks", new_user_task_path(current_user),  class: 'btn btn-primary btn-mini' %>
<br><br>


<table id = "tasks" class = "filterable">
  <thead>
      <tr> 
          <th>Name</th>
          <th>Description</th>
          <th>Category</th>
          <th>Days Left</th>
          <th>Due Date</th>
          <th>Complete</th>
      </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task|  %>    
      <tr>
          <td><%= task.name%></td> 
          <td><%= task.description%></td>
          <td><%= task.category%></td>  
          <td><%= task.time_remaining%></td>
          <td><%= task.due_date%></td>
          <td><%= check_box_tag "task_id[]", task.id, checked = task.complete%></td> 
      </tr> 
  <% end %>
  </tbody>
</table>
<br>

app/views/tasks/new.html.erb
<h1> Create Task </h1>
<%= form_for([current_user, @task]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.submit "Save" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/show.html.erb
<h1>User Home</h1>